[package]
name = "paradex"
version = "0.4.2"
edition = "2021"
license = "MIT"
description = "Paradex client library"
repository  = "https://github.com/snow-avocado/paradex-rs"

[dependencies]
cached = "0.55.1"
chrono = "0.4.40"
futures-util = "0.3.31"
indexmap = "2.7.1"
jsonrpsee-core = "0.24.8"
jsonrpsee-types = "0.24.8"
log = "0.4.26"
reqwest =  {version="0.12.12", features=["json"]}
rust_decimal = {version="1.36.0", features=["serde"]}
serde = "1.0.218"
serde_json = "1.0.140"
simple_logger = "5.0.0"
starknet-core = "0.12.1"
starknet-crypto = "0.7.4"
starknet-signers = "0.10.2"
thiserror = "2.0.12"
tokio = { version = "1.43.0", features=["full"]}
tokio-tungstenite = {version = "0.26.2", features=["native-tls"]}

[dev-dependencies]
criterion = "0.5.1"
mimalloc = "0.1.43"

[profile.bench]
debug = true

[[bench]]
name = "order_sign"
harness = false
