[package]
name = "paradex-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Paradex client library"
repository  = "https://github.com/snow-avocado/paradex-rs"

[dependencies]
cached = "0.54.0"
futures-util = "0.3.31"
indexmap = "2.7.1"
jsonrpsee-core = "0.24.7"
jsonrpsee-types = "0.24.7"
log = "0.4.25"
reqwest =  {version="0.12.12", features=["json"]}
rust_decimal = {version="1.36.0", features=["serde"]}
serde = "1.0.217"
serde_json = "1.0.137"
simple_logger = "5.0.0"
starknet-core = "0.12.1"
starknet-crypto = "0.7.4"
starknet-signers = "0.10.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features=["full"]}
tokio-tungstenite = {version = "0.26.1", features=["native-tls"]}
tokio-util = "0.7.13"

[dev-dependencies]
criterion = "0.5.1"

[profile.bench]
debug = true

[[bench]]
name = "order_sign"
harness = false
